version: 2

python:
  version: 3
  install:
    - requirements: docs/source/requirements_rtd.txt
    - method: pip
      path: .

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true
